### ISSUE TITLE
Add index failed, err: unrecognized token: ""

### ISSUE THREAD

**Issue by nisharyan** [milvus-io/milvus-lite#250]
Is there any limitation on the naming scheme for a collection in milvus lite (Other the ones mentioned here - https://milvus.io/docs/v2.4.x/limitations.md)

For specific collection_name patterns, I am facing this issue 
```
E20250203 03:04:19.604835 3110428 collection_meta.cpp:148] [SERVER][CreateIndex][grpcpp_sync_ser] Add index failed, err: unrecognized token: ""
RPC error: [create_index], <MilvusException: (code=5, message=: internal error)>, <Time:{'RPC start': '2025-02-03 03:04:19.602683', 'RPC error': '2025-02-03 03:04:19.606538'}>
Failed to create an index on collection: test_collection_guppnxkmee
```
Script to reproduce

```
client = MilvusClient(
    "./test_demo.db",
)
client.create_collection(collection_name="test_collection_guppnxkmee", dimension=384)
```

pymilvus version - 2.4.9

**Comment by xiaofan-luan** [comment]
the name looks to have some special character?

 unrecognized token: "�"

from the collection name it seems to be fine.  

from pymilvus import MilvusClient
client = MilvusClient("./milvus_demo.db")

client.create_collection(
    collection_name="test_collection_guppnxkmee",
    dimension=384  # The dimension of your vectors
)

seems to be all good from my laptop

**Comment by nisharyan** [comment]
```
from pymilvus import MilvusClient
client = MilvusClient("./milvus_demo.db")

client.create_collection(
collection_name="test_collection_guppnxkmee",
dimension=384 # The dimension of your vectors
)
```
Also gave me this same error. Need some one else to validate this

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 


could you help to verify this issue?

**Comment by yanliang567** [comment]
working for me. I can successfully create a collection "test_collection_guppnxkmee" with milvus_lite

**Comment by yanliang567** [comment]
@nisharyan maybe you could try to upgrade to the latest pymilvus

/assign @nisharyan 
/unassign

**Comment by nisharyan** [comment]
I have a distributed milvus running in kubernetes cluster and I am using milvus lite for testing. I need to maintain parity between the server and client library versions. I am currently running milvus 2.4.17 and so is pymilvus 2.5.x compatible with milvus 2.4.x?

**Comment by yanliang567** [comment]
what about using a python virtual environment for pymilvus 2.5.x? BTW, I doubt that there is something wrong with the character encoding, such as utf-8?

**Comment by nisharyan** [comment]
```
unique_collection_key = "".join(
    random.choices(string.ascii_lowercase, k=5)
)
return f"test_collection_{unique_collection_key}"
```

Not sure if it's a milvus lite error. Will close this for now
Thank you for the assistance

**Comment by nisharyan** [comment]
By next version, is it 2.4.xx or 2.5.xx?

**Comment by junjiejiangjjj** [comment]
> By next version, is it 2.4.xx or 2.5.xx?

2.4.xx

**Comment by nisharyan** [comment]
Thank you @junjiejiangjjj

**Comment by nisharyan** [comment]
Is there a safe way to generate random collection name until then?
Or is there a pattern that's causing this error?

**Comment by junjiejiangjjj** [comment]
> Is there a safe way to generate random collection name until then? Or is there a pattern that's causing this error?

It is unclear which names will cause this error, but we will release a new version next week so that you can wait a little longer.

**Comment by assaftibm** [comment]
I'm getting the same error with:
```bash
langchain-milvus          0.1.8
milvus-lite               2.4.11
pymilvus                  2.5.5
```

**Comment by junjiejiangjjj** [comment]
This issue was fixed in milvus-lite 2.4.12

**Comment by nisharyan** [comment]
I am getting the same error for it even in 2.4.12
collection name: test_collection_escck

**Comment by junjiejiangjjj** [comment]
> I am getting the same error even in 2.4.12 collection names: test_collection_escck, test_collection_erunv

It runs normally on MacOS, but there is a problem with Ubuntu. I will continue to solve this problem

**Comment by nisharyan** [comment]
Thank you @junjiejiangjjj !!

**Comment by Luux** [comment]
I run into the same issue and can confirm that the issue still persists. I ran into this because tests suddenly failed, which used to create a collection named `c_testproject`. As soon as I change the name to something else, for example `c_testprojec` or `c_testprojecta`, it works without error.

Further, I can confirm that the names provided by @nisharyan also cause the issue consistently (tested with `test_collection_escck`).

Versions: Python 3.12.9
```
> pip freeze | grep "milvus"                  
langchain-milvus==0.1.10
milvus-lite==2.4.12
pymilvus==2.5.9
```

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble

```
